/*
  StarCraft: Brood War 빌드오더 연습기 - 데이터 테이블
  비용/시간/인구수 수치는 실제 게임 값에 최대한 가깝게 맞춘 "연습용 근사치"입니다.
  (일꾼 채집 속도 등은 커뮤니티에서 통용되는 근사 공식을 사용했습니다.)
*/

// 일꾼 1명당 초당 채집량 근사치 (미네랄/가스 공통)
const GATHER_RATE_PER_WORKER = 0.70;
// 저그 라바 재생 주기(초)
const LARVA_SPAWN_INTERVAL = 15;
const LARVA_CAP_PER_HATCH = 3;

const RACES = {
  terran: {
    id: 'terran', name: '테란', workerName: 'SCV', mainBuildingId: 'command_center',
    startMinerals: 50, startGas: 0, startWorkers: 4, startSupplyUsed: 4, startSupplyCap: 10,
    gasBuildingId: 'refinery',
    buildings: {
      command_center:   { name: '커맨드 센터', mineral: 400, gas: 0, time: 120, supply: 10, prereq: [], produces: ['scv'] },
      supply_depot:      { name: '서플라이 디폿', mineral: 100, gas: 0, time: 40, supply: 8, prereq: [] },
      refinery:          { name: '리파이너리', mineral: 100, gas: 0, time: 40, supply: 0, prereq: [] },
      barracks:          { name: '배럭스', mineral: 150, gas: 0, time: 80, supply: 0, prereq: [], produces: ['marine', 'firebat', 'medic', 'ghost'] },
      engineering_bay:   { name: '엔지니어링 베이', mineral: 125, gas: 0, time: 60, supply: 0, prereq: [] },
      bunker:            { name: '벙커', mineral: 100, gas: 0, time: 30, supply: 0, prereq: ['barracks'] },
      missile_turret:    { name: '미사일 터렛', mineral: 75, gas: 0, time: 30, supply: 0, prereq: ['engineering_bay'] },
      academy:           { name: '아카데미', mineral: 150, gas: 0, time: 80, supply: 0, prereq: ['barracks'] },
      factory:           { name: '팩토리', mineral: 200, gas: 100, time: 80, supply: 0, prereq: ['barracks'], produces: ['vulture', 'siege_tank', 'goliath'] },
      machine_shop:      { name: '머신샵 (애드온)', mineral: 50, gas: 50, time: 40, supply: 0, prereq: ['factory'], isAddon: true },
      armory:            { name: '아머리', mineral: 100, gas: 50, time: 80, supply: 0, prereq: ['factory'] },
      starport:          { name: '스타포트', mineral: 150, gas: 100, time: 70, supply: 0, prereq: ['factory'], produces: ['wraith', 'dropship', 'science_vessel', 'battlecruiser', 'valkyrie'] },
      control_tower:     { name: '컨트롤 타워 (애드온)', mineral: 50, gas: 50, time: 40, supply: 0, prereq: ['starport'], isAddon: true },
      science_facility:  { name: '사이언스 퍼실리티', mineral: 100, gas: 150, time: 80, supply: 0, prereq: ['starport'] },
      covert_ops:        { name: '커버트 옵스 (애드온)', mineral: 50, gas: 50, time: 40, supply: 0, prereq: ['science_facility'], isAddon: true },
      physics_lab:       { name: '피직스 랩 (애드온)', mineral: 50, gas: 50, time: 50, supply: 0, prereq: ['science_facility'], isAddon: true },
    },
    units: {
      scv:            { name: 'SCV', mineral: 50, gas: 0, time: 20, supply: 1, from: 'command_center', prereq: [] },
      marine:         { name: '마린', mineral: 50, gas: 0, time: 24, supply: 1, from: 'barracks', prereq: [] },
      firebat:        { name: '파이어뱃', mineral: 50, gas: 25, time: 24, supply: 1, from: 'barracks', prereq: ['academy'] },
      medic:          { name: '메딕', mineral: 50, gas: 25, time: 30, supply: 1, from: 'barracks', prereq: ['academy'] },
      ghost:          { name: '고스트', mineral: 25, gas: 75, time: 50, supply: 1, from: 'barracks', prereq: ['academy', 'covert_ops'] },
      vulture:        { name: '벌처', mineral: 75, gas: 0, time: 30, supply: 2, from: 'factory', prereq: [] },
      siege_tank:     { name: '시즈 탱크', mineral: 150, gas: 100, time: 50, supply: 2, from: 'factory', prereq: [] },
      goliath:        { name: '골리앗', mineral: 100, gas: 50, time: 40, supply: 2, from: 'factory', prereq: ['armory'] },
      wraith:         { name: '레이스', mineral: 150, gas: 100, time: 60, supply: 2, from: 'starport', prereq: [] },
      dropship:       { name: '드랍십', mineral: 100, gas: 100, time: 50, supply: 2, from: 'starport', prereq: [] },
      science_vessel: { name: '사이언스 베슬', mineral: 100, gas: 225, time: 80, supply: 2, from: 'starport', prereq: ['science_facility'] },
      battlecruiser:  { name: '배틀크루저', mineral: 400, gas: 300, time: 133, supply: 6, from: 'starport', prereq: ['physics_lab'] },
      valkyrie:       { name: '발키리', mineral: 250, gas: 125, time: 60, supply: 3, from: 'starport', prereq: ['armory'] },
    },
  },

  zerg: {
    id: 'zerg', name: '저그', workerName: '드론', mainBuildingId: 'hatchery',
    startMinerals: 50, startGas: 0, startWorkers: 4, startSupplyUsed: 4, startSupplyCap: 9,
    gasBuildingId: 'extractor',
    buildings: {
      hatchery:          { name: '해처리', mineral: 300, gas: 0, time: 120, supply: 1, prereq: [], consumesWorker: true },
      spawning_pool:     { name: '스포닝 풀', mineral: 200, gas: 0, time: 80, supply: 0, prereq: [], consumesWorker: true },
      extractor:         { name: '익스트랙터', mineral: 50, gas: 0, time: 40, supply: 0, prereq: [], consumesWorker: true },
      evolution_chamber: { name: '에볼루션 챔버', mineral: 75, gas: 0, time: 40, supply: 0, prereq: [], consumesWorker: true },
      hydralisk_den:     { name: '히드라리스크 덴', mineral: 100, gas: 50, time: 40, supply: 0, prereq: ['spawning_pool'], consumesWorker: true },
      lair:              { name: '레어 (변태)', mineral: 150, gas: 100, time: 100, supply: 0, prereq: ['hatchery', 'spawning_pool'], consumesWorker: false },
      spire:             { name: '스파이어', mineral: 200, gas: 150, time: 120, supply: 0, prereq: ['lair'], consumesWorker: true },
      queens_nest:       { name: '퀸즈 네스트', mineral: 150, gas: 100, time: 60, supply: 0, prereq: ['lair'], consumesWorker: true },
      hive:              { name: '하이브 (변태)', mineral: 200, gas: 150, time: 100, supply: 0, prereq: ['queens_nest'], consumesWorker: false },
      ultralisk_cavern:  { name: '울트라리스크 캐번', mineral: 150, gas: 200, time: 80, supply: 0, prereq: ['hive'], consumesWorker: true },
      defiler_mound:     { name: '디파일러 마운드', mineral: 100, gas: 100, time: 60, supply: 0, prereq: ['hive'], consumesWorker: true },
    },
    units: {
      drone:     { name: '드론', mineral: 50, gas: 0, time: 20, supply: 1, from: 'larva', prereq: [] },
      overlord:  { name: '오버로드', mineral: 100, gas: 0, time: 40, supply: -8, from: 'larva', prereq: [] },
      zergling:  { name: '저글링 x2', mineral: 50, gas: 0, time: 28, supply: 1, from: 'larva', prereq: ['spawning_pool'] },
      hydralisk: { name: '히드라리스크', mineral: 75, gas: 25, time: 28, supply: 1, from: 'larva', prereq: ['hydralisk_den'] },
      mutalisk:  { name: '뮤탈리스크', mineral: 100, gas: 100, time: 40, supply: 2, from: 'larva', prereq: ['spire'] },
      scourge:   { name: '스커지 x2', mineral: 50, gas: 150, time: 40, supply: 1, from: 'larva', prereq: ['spire'] },
      queen:     { name: '퀸', mineral: 100, gas: 100, time: 50, supply: 2, from: 'larva', prereq: ['queens_nest'] },
      defiler:   { name: '디파일러', mineral: 50, gas: 150, time: 50, supply: 2, from: 'larva', prereq: ['defiler_mound'] },
      ultralisk: { name: '울트라리스크', mineral: 200, gas: 200, time: 60, supply: 4, from: 'larva', prereq: ['ultralisk_cavern'] },
    },
  },

  protoss: {
    id: 'protoss', name: '프로토스', workerName: '프로브', mainBuildingId: 'nexus',
    startMinerals: 50, startGas: 0, startWorkers: 4, startSupplyUsed: 4, startSupplyCap: 9,
    gasBuildingId: 'assimilator',
    buildings: {
      nexus:               { name: '넥서스', mineral: 400, gas: 0, time: 120, supply: 9, prereq: [], produces: ['probe'] },
      pylon:                { name: '파일런', mineral: 100, gas: 0, time: 40, supply: 8, prereq: [] },
      assimilator:          { name: '어시밀레이터', mineral: 100, gas: 0, time: 40, supply: 0, prereq: [] },
      gateway:              { name: '게이트웨이', mineral: 150, gas: 0, time: 60, supply: 0, prereq: ['pylon'], produces: ['zealot', 'dragoon', 'high_templar', 'dark_templar'] },
      forge:                { name: '포지', mineral: 150, gas: 0, time: 40, supply: 0, prereq: ['pylon'] },
      photon_cannon:        { name: '포톤 캐논', mineral: 150, gas: 0, time: 40, supply: 0, prereq: ['forge'] },
      cybernetics_core:     { name: '사이버네틱스 코어', mineral: 200, gas: 0, time: 60, supply: 0, prereq: ['gateway'] },
      citadel_of_adun:      { name: '시타델 오브 아둔', mineral: 150, gas: 0, time: 60, supply: 0, prereq: ['gateway'] },
      templar_archives:     { name: '템플러 아카이브', mineral: 150, gas: 200, time: 60, supply: 0, prereq: ['citadel_of_adun', 'cybernetics_core'] },
      robotics_facility:    { name: '로보틱스 퍼실리티', mineral: 200, gas: 200, time: 80, supply: 0, prereq: ['cybernetics_core'] },
      observatory:          { name: '옵저버토리', mineral: 50, gas: 100, time: 40, supply: 0, prereq: ['robotics_facility'] },
      robotics_support_bay: { name: '로보틱스 서포트 베이', mineral: 150, gas: 100, time: 30, supply: 0, prereq: ['robotics_facility'] },
      stargate:             { name: '스타게이트', mineral: 150, gas: 150, time: 70, supply: 0, prereq: ['cybernetics_core'] },
      fleet_beacon:         { name: '플릿 비컨', mineral: 300, gas: 200, time: 60, supply: 0, prereq: ['stargate'] },
      arbiter_tribunal:     { name: '아비터 트리뷰널', mineral: 200, gas: 150, time: 60, supply: 0, prereq: ['templar_archives', 'stargate'] },
    },
    units: {
      probe:        { name: '프로브', mineral: 50, gas: 0, time: 20, supply: 1, from: 'nexus', prereq: [] },
      zealot:       { name: '질럿', mineral: 100, gas: 0, time: 40, supply: 2, from: 'gateway', prereq: [] },
      dragoon:      { name: '드라군', mineral: 125, gas: 50, time: 50, supply: 2, from: 'gateway', prereq: ['cybernetics_core'] },
      high_templar: { name: '하이템플러', mineral: 50, gas: 150, time: 50, supply: 2, from: 'gateway', prereq: ['templar_archives'] },
      dark_templar: { name: '다크템플러', mineral: 125, gas: 100, time: 50, supply: 2, from: 'gateway', prereq: ['templar_archives'] },
      shuttle:      { name: '셔틀', mineral: 200, gas: 0, time: 60, supply: 2, from: 'robotics_facility', prereq: [] },
      reaver:       { name: '리버', mineral: 200, gas: 100, time: 70, supply: 4, from: 'robotics_facility', prereq: ['robotics_support_bay'] },
      observer:     { name: '옵저버', mineral: 25, gas: 75, time: 40, supply: 1, from: 'robotics_facility', prereq: ['observatory'] },
      corsair:      { name: '커세어', mineral: 150, gas: 100, time: 40, supply: 2, from: 'stargate', prereq: [] },
      scout:        { name: '스카우트', mineral: 275, gas: 125, time: 80, supply: 3, from: 'stargate', prereq: [] },
      carrier:      { name: '캐리어', mineral: 350, gas: 250, time: 140, supply: 6, from: 'stargate', prereq: ['fleet_beacon'] },
      arbiter:      { name: '아비터', mineral: 100, gas: 350, time: 160, supply: 4, from: 'stargate', prereq: ['arbiter_tribunal'] },
    },
  },
};

// 빌드오더 트리거: { supply } 또는 { time(초) } 중 하나 이상 지정. 둘 다 있으면 둘 다 표시.
// action: { kind: 'build'|'train'|'gas', id, count }
const BUILD_ORDERS = {
  terran: [
    {
      id: 't_1rax_fe', name: '1배럭 더블 (1 Rax FE)', level: '입문',
      desc: '배럭스 하나로 벙커 압박 없이 안전하게 멀티를 가져가는 표준 확장 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' }, note: '9 서플라이 디폿' },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' }, note: '10 배럭스' },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'refinery' }, note: '가스 확보' },
        { trigger: { minerals: 400, time: 130 }, action: { kind: 'build', id: 'command_center' }, note: '두 번째 커맨드 센터 (멀티)' },
        { trigger: { supply: 14 }, action: { kind: 'train', id: 'marine' }, note: '마린 생산 시작' },
        { trigger: { supply: 15 }, action: { kind: 'build', id: 'supply_depot' }, note: '추가 서플라이' },
        { trigger: { supply: 16 }, action: { kind: 'build', id: 'academy' }, note: '아카데미' },
      ],
    },
    {
      id: 't_8rax_rush', name: '8배럭 러시', level: '입문',
      desc: '인구수 8에 배럭스를 올려 마린을 최대한 빨리 뽑는 초반 압박 빌드.',
      steps: [
        { trigger: { supply: 8 }, action: { kind: 'build', id: 'barracks' }, note: '8 배럭스' },
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' }, note: '9 서플라이 디폿' },
        { trigger: { supply: 10 }, action: { kind: 'train', id: 'marine' }, note: '마린 연속 생산' },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'bunker' }, note: '전진 벙커' },
      ],
    },
    {
      id: 't_5rax_marines', name: '5배럭 마린 올인', level: '중급',
      desc: '배럭스 5개를 동시에 돌려 마린 물량으로 밀어붙이는 올인 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'barracks' }, note: '배럭스 추가' },
        { trigger: { supply: 14 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 16 }, action: { kind: 'build', id: 'barracks' }, note: '배럭스 3' },
        { trigger: { supply: 18 }, action: { kind: 'build', id: 'barracks' }, note: '배럭스 4' },
        { trigger: { supply: 20 }, action: { kind: 'build', id: 'barracks' }, note: '배럭스 5' },
        { trigger: { supply: 22 }, action: { kind: 'build', id: 'supply_depot' } },
      ],
    },
    {
      id: 't_111_siege_expand', name: '1-1-1 시즈 확장', level: '중급',
      desc: '배럭스-팩토리-스타포트 각 1개씩 올리며 시즈탱크 체제로 넘어가는 확장 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'refinery' } },
        { trigger: { supply: 13 }, action: { kind: 'build', id: 'factory' } },
        { trigger: { supply: 15 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { minerals: 400 }, action: { kind: 'build', id: 'command_center' }, note: '멀티' },
        { trigger: { supply: 17 }, action: { kind: 'build', id: 'machine_shop' }, note: '시즈모드 연구용 애드온' },
        { trigger: { supply: 18 }, action: { kind: 'train', id: 'siege_tank' } },
        { trigger: { supply: 20 }, action: { kind: 'build', id: 'starport' } },
      ],
    },
    {
      id: 't_2fact_vulture', name: '2팩토리 벌처 하라스', level: '중급',
      desc: '팩토리 2개로 벌처를 쏟아내 상대 일꾼 라인을 견제하는 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'refinery' } },
        { trigger: { supply: 13 }, action: { kind: 'build', id: 'factory' } },
        { trigger: { supply: 15 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 16 }, action: { kind: 'build', id: 'factory' }, note: '팩토리 2' },
        { trigger: { supply: 18 }, action: { kind: 'train', id: 'vulture' } },
        { trigger: { supply: 19 }, action: { kind: 'train', id: 'vulture' } },
      ],
    },
    {
      id: 't_wraith_rush', name: '레이스 러시', level: '고급',
      desc: '공중 유닛 레이스로 초반 기습을 노리는 테크 러시 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'refinery' } },
        { trigger: { supply: 13 }, action: { kind: 'build', id: 'factory' } },
        { trigger: { supply: 15 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 16 }, action: { kind: 'build', id: 'starport' } },
        { trigger: { supply: 18 }, action: { kind: 'build', id: 'control_tower' }, note: '클로킹용 애드온' },
        { trigger: { supply: 19 }, action: { kind: 'train', id: 'wraith' } },
        { trigger: { supply: 21 }, action: { kind: 'train', id: 'wraith' } },
      ],
    },
    {
      id: 't_bc_tech', name: '배틀크루저 테크 러시', level: '고급',
      desc: '멀티를 낀 상태로 빠르게 배틀크루저 테크를 올리는 장기전 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'refinery' } },
        { trigger: { minerals: 400 }, action: { kind: 'build', id: 'command_center' } },
        { trigger: { supply: 14 }, action: { kind: 'build', id: 'factory' } },
        { trigger: { supply: 17 }, action: { kind: 'build', id: 'starport' } },
        { trigger: { supply: 19 }, action: { kind: 'build', id: 'science_facility' } },
        { trigger: { supply: 20 }, action: { kind: 'build', id: 'physics_lab' } },
        { trigger: { supply: 24 }, action: { kind: 'train', id: 'battlecruiser' } },
      ],
    },
    {
      id: 't_bunker_rush', name: '벙커링', level: '중급',
      desc: '적 진영 앞에 벙커를 박아 초반부터 압박하는 공격적 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { supply: 11 }, action: { kind: 'train', id: 'scv' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'bunker' }, note: '적 앞마당 근처 전진 벙커' },
        { trigger: { supply: 13 }, action: { kind: 'train', id: 'marine' } },
        { trigger: { supply: 14 }, action: { kind: 'train', id: 'marine' } },
      ],
    },
    {
      id: 't_turtle_fe', name: '터렛 확장 (터틀 FE)', level: '중급',
      desc: '엔지니어링 베이 + 미사일 터렛으로 멀티를 단단하게 방어하는 수비형 확장.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { minerals: 400 }, action: { kind: 'build', id: 'command_center' } },
        { trigger: { supply: 13 }, action: { kind: 'build', id: 'engineering_bay' } },
        { trigger: { supply: 14 }, action: { kind: 'build', id: 'missile_turret' } },
        { trigger: { supply: 15 }, action: { kind: 'build', id: 'missile_turret' }, note: '멀티 앞 터렛 2기' },
        { trigger: { supply: 16 }, action: { kind: 'build', id: 'refinery' } },
      ],
    },
    {
      id: 't_1_1_1_goliath', name: '1배럭 2팩토리 골리앗', level: '고급',
      desc: '골리앗 물량으로 공중 유닛에 강한 지상+대공 조합을 만드는 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'refinery' } },
        { trigger: { supply: 13 }, action: { kind: 'build', id: 'factory' } },
        { trigger: { supply: 15 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 16 }, action: { kind: 'build', id: 'armory' } },
        { trigger: { supply: 17 }, action: { kind: 'build', id: 'factory' }, note: '팩토리 2' },
        { trigger: { supply: 19 }, action: { kind: 'train', id: 'goliath' } },
        { trigger: { supply: 21 }, action: { kind: 'train', id: 'goliath' } },
      ],
    },
    {
      id: 't_valkyrie_def', name: '발키리 방어 빌드', level: '고급',
      desc: '대공 특화 발키리로 상대 공중 유닛을 무력화하는 방어형 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'refinery' } },
        { trigger: { supply: 13 }, action: { kind: 'build', id: 'factory' } },
        { trigger: { supply: 16 }, action: { kind: 'build', id: 'armory' } },
        { trigger: { supply: 18 }, action: { kind: 'build', id: 'starport' } },
        { trigger: { supply: 20 }, action: { kind: 'train', id: 'valkyrie' } },
        { trigger: { supply: 23 }, action: { kind: 'train', id: 'valkyrie' } },
      ],
    },
    {
      id: 't_fast_cc', name: '노 배럭 더블 (배럭 없는 확장)', level: '고급',
      desc: '배럭스보다 멀티를 먼저 올리는 극단적 economy 우선 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'supply_depot' } },
        { trigger: { minerals: 400, supply: 10 }, action: { kind: 'build', id: 'command_center' }, note: '배럭 없이 바로 멀티' },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'barracks' } },
        { trigger: { supply: 14 }, action: { kind: 'build', id: 'refinery' } },
        { trigger: { supply: 15 }, action: { kind: 'build', id: 'supply_depot' } },
      ],
    },
  ],

  zerg: [
    {
      id: 'z_9pool_ovie', name: '9드론 오버로드 표준', level: '입문',
      desc: '표준적인 저그 시작 빌드. 오버로드로 인구수를 관리하며 안정적으로 풀어나간다.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'train', id: 'overlord' }, note: '9 오버로드' },
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'spawning_pool' }, note: '스포닝 풀' },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'extractor' }, note: '가스 확보' },
        { trigger: { minerals: 300 }, action: { kind: 'build', id: 'hatchery' }, note: '멀티 해처리' },
        { trigger: { supply: 13 }, action: { kind: 'train', id: 'zergling' } },
      ],
    },
    {
      id: 'z_6pool_ling', name: '6풀 저글링 러시', level: '중급',
      desc: '인구수 6에 스포닝 풀을 올려 최대한 빠르게 저글링을 뽑는 초반 러시.',
      steps: [
        { trigger: { supply: 6 }, action: { kind: 'build', id: 'spawning_pool' }, note: '6 스포닝 풀' },
        { trigger: { supply: 8 }, action: { kind: 'train', id: 'overlord' } },
        { trigger: { supply: 9 }, action: { kind: 'train', id: 'zergling' } },
        { trigger: { supply: 11 }, action: { kind: 'train', id: 'zergling' } },
      ],
    },
    {
      id: 'z_mutal_tech', name: '뮤탈리스크 테크 러시', level: '고급',
      desc: '레어 - 스파이어로 빠르게 넘어가 뮤탈리스크 다수로 공중 견제를 시작하는 빌드.',
      steps: [
        { trigger: { supply: 9 }, action: { kind: 'train', id: 'overlord' } },
        { trigger: { supply: 9 }, action: { kind: 'build', id: 'spawning_pool' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'extractor' } },
        { trigger: { minerals: 300 }, action: { kind: 'build', id: 'hatchery' } },
        { trigger: { supply: 14 }, action: { kind: 'build', id: 'lair' } },
        { trigger: { supply: 16 }, action: { kind: 'train', id: 'overlord' } },
        { trigger: { supply: 18 }, action: { kind: 'build', id: 'spire' } },
        { trigger: { supply: 22 }, action: { kind: 'train', id: 'mutalisk' } },
      ],
    },
  ],

  protoss: [
    {
      id: 'p_1gate_core', name: '1게이트 사이버네틱스 코어 표준', level: '입문',
      desc: '가장 기본적인 프로토스 스탠다드 빌드. 드라군 테크로 안정적으로 확장한다.',
      steps: [
        { trigger: { supply: 8 }, action: { kind: 'build', id: 'pylon' }, note: '8 파일런' },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'gateway' }, note: '게이트웨이' },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'assimilator' }, note: '가스 확보' },
        { trigger: { supply: 13 }, action: { kind: 'build', id: 'cybernetics_core' } },
        { trigger: { supply: 15 }, action: { kind: 'build', id: 'pylon' } },
        { trigger: { minerals: 400 }, action: { kind: 'build', id: 'nexus' }, note: '멀티' },
        { trigger: { supply: 16 }, action: { kind: 'train', id: 'dragoon' } },
      ],
    },
    {
      id: 'p_forge_ff', name: '포지 캐논 방어', level: '중급',
      desc: '포지와 포톤 캐논으로 앞마당을 단단히 방어하며 확장하는 수비형 빌드.',
      steps: [
        { trigger: { supply: 8 }, action: { kind: 'build', id: 'pylon' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'forge' } },
        { trigger: { minerals: 400 }, action: { kind: 'build', id: 'nexus' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'photon_cannon' } },
        { trigger: { supply: 13 }, action: { kind: 'build', id: 'photon_cannon' } },
        { trigger: { supply: 14 }, action: { kind: 'build', id: 'gateway' } },
      ],
    },
    {
      id: 'p_dt_rush', name: '다크템플러 러시', level: '고급',
      desc: '시타델 오브 아둔 - 템플러 아카이브로 빠르게 다크템플러를 확보하는 기습 빌드.',
      steps: [
        { trigger: { supply: 8 }, action: { kind: 'build', id: 'pylon' } },
        { trigger: { supply: 10 }, action: { kind: 'build', id: 'gateway' } },
        { trigger: { supply: 12 }, action: { kind: 'build', id: 'assimilator' } },
        { trigger: { supply: 13 }, action: { kind: 'build', id: 'citadel_of_adun' } },
        { trigger: { supply: 15 }, action: { kind: 'build', id: 'pylon' } },
        { trigger: { supply: 16 }, action: { kind: 'build', id: 'cybernetics_core' } },
        { trigger: { supply: 18 }, action: { kind: 'build', id: 'templar_archives' } },
        { trigger: { supply: 20 }, action: { kind: 'train', id: 'dark_templar' } },
      ],
    },
  ],
};
